[build]
  command = "make build"
  publish = "site"

[build.environment]
  GO_IMPORT_PATH = "github.com/eyalch/kurzr"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/kurzr/:splat"
  status = 200
